name: el_afrik_restaurant
description: "El Afrik Restaurant App. Developed by Azmir Khan."


version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_gen_runner: ^5.12.0
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.1.1
  mobile_scanner: ^7.1.4
  flutter_dotenv: ^6.0.0
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0
  http: ^1.6.0
  dio: ^5.9.0
  get_storage: ^2.1.1
  flutter_image_compress: ^2.4.0
  google_places_flutter: ^2.1.1
  flutter_html: ^3.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  table_calendar: ^3.2.0
  upgrader: ^12.5.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.10.4



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/dummy/
    - assets/gifs/
    - .env

  fonts:
    - family: Peridot
      fonts:
        - asset: assets/fonts/peridot_pe_variable.otf

flutter_gen:
  output: lib/utils/assets_gen

flutter_native_splash:

  color: "#FFFFFF"  ##====================================[REQUIRED]==========
  image: assets/images/logo1024.png
  fullscreen: true
  android_12:
    # background color
    color: "#FFFFFF"
    image: assets/images/logo1024.png
    # center-logo background color
    icon_background_color: "#B0E7C6"
